version: '3'

services:
  pgvector:
    container_name: vaic
    image: pgvector/pgvector:pg13
    environment:
      POSTGRES_DB: iga_veos_ai_db
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
volumes:
  open-webui:
